#! /bin/bash


flash_disk=/dev/sdb
sd_image=phytec-qt5demo-image-phyboard-segin-imx6ul-2.sdcard
accept=no

/usr/bin/python3 ${HOME}/work/prj/python/python-learn/find_usb_device.py

echo 'Input full disk name: '
read flash_disk

# echo 'Show disks:'
# ls /dev/sd[b-z]

# echo 'Enter flash-disk:'
# read flash_disk

echo 'Check disk:'
ls -la $flash_disk

echo 'Show image:'
ls deploy/images/phyboard-segin-imx6ul-2/*.sdcard

echo 'Enter image name:'
read sd_image

echo 'Check image:'
ls -la $sd_image

echo "Unmount partition 2 and 1"
sudo umount ${flash_disk}[1-9]
#sudo umount ${flash_disk}2
#sudo umount ${flash_disk}1

#echo 'Write image? (yes/no):'
#read accept
#echo "Your ansver: $accept"

#if [ $accept != yes ]; then
#   echo 'Exit...'
#   exit 
#fi

file_size=$(wc -c <"$sd_image")
echo "Image size: $file_size"

echo "flash-disk: $flash_disk"
echo "image: $sd_image"

#echo 'Does low level format? (yes):'
#read accept

#if [ $accept == yes ]; then
#   echo "Formating ..."
#   sudo dd if=/dev/zero of=/dev/sdb && echo "Susses!"
#fi


echo "Write image to flash-disk..."
sudo dd if=${sd_image} of=${flash_disk} bs=1M && sync

echo "Read sd-flash to image.bin..."
dd if=${sd_image} of=image.bin iflag=count_bytes count=${file_size}

echo "Verify image..."
diff image.bin ${sd_image} || echo "FAIL!!!"

rm image.bin

#sudo dd if=${sd_image} bs=1MB | pv | sudo dd of=${flash_disk} bs=1MB conv=fsync
#pv -n ${sd_image} -s ${file_size} | sudo dd of=${flash_disk} bs=1MB conv=fsync
#sudo dd if=$sd_image of=$flash_disk bs=1MB conv=fsync status=progress
#sudo dd if=${sd_image} | pv | sudo dd of=${flash_disk} bs=1MB conv=fsync


