#! /bin/bash

device=/dev/sdb1
accept=no

echo "Enter flash-device partition:"
ls /dev/sd[b-z]1
read device

mkdir sd-card
sudo mount ${device} ./sd-card -o users
echo "Check device:"
ls -la ./sd-card

echo "Continue (yes/no, default - yes)?"
read accept
if [ -z $accept ]; then
	echo "Writing..."
else
	if [ $accept != yes ]; then
		sudo umount ./sd-card
		echo 'Exit...'
   		exit 
   	fi	
   	echo "Writing..."
fi

cp -f deploy/images/phyboard-segin-imx6ul-2/zImage   										./sd-card/zImage
cp -f deploy/images/phyboard-segin-imx6ul-2/zImage-imx6ul-phytec-phyboard-segin-ff-rdk.dtb	./sd-card/oftree

echo "Check partition:"
ls -la ./sd-card/

sudo umount ./sd-card
